unit Model.Customer;

interface

uses
  MVCFramework.Serializer.Commons,
  MVCFramework.ActiveRecord,
  System.Classes;

type

  [MVCNameCase(ncCamelCase)]
  [MVCTable('customers')]
  TCustomerModel = class(TMVCActiveRecord)
  private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    fID: Integer;
    [MVCTableField('code')]
    fCode: String;
    [MVCTableField('description')]
    fDescription: String;
    [MVCTableField('city')]
    fCity: String;
    [MVCTableField('note')]
    fNote: String;
    [MVCTableField('rating')]
    fRating: Integer;
  public
    constructor Create; override;
    destructor Destroy; override;
    property ID: Integer read fID write fID;
    property Code: String read fCode write fCode;
    property Description: String read fDescription write fDescription;
    property City: String read fCity write fCity;
    property Note: String read fNote write fNote;
    property Rating: Integer read fRating write fRating;
  end;

implementation

constructor TCustomerModel.Create;
begin
  inherited Create;
end;

destructor TCustomerModel.Destroy;
begin
  inherited;
end;

initialization

  ActiveRecordMappingRegistry.AddEntity('customers', TCustomerModel);

end.


